### ISSUE TITLE
preprocess hyper-parameters for pre-training

### ISSUE THREAD

**Issue by yuzhenmao** [bowang-lab/scGPT#102]
Hi,

Thank you for the amazing work! May I ask about the preprocess hyper-parameters you used in the pre-training process? It should be something similar to the one in the tutorial:

<img width="444" alt="Screenshot 2023-10-24 at 9 37 37 PM" src="https://github.com/bowang-lab/scGPT/assets/57878927/2940b8d1-04da-4063-a3f6-1f1199819d5c">

Thanks!

**Comment by subercui** [comment]
Hi, the pretraining does not use this preprocessor, primarily due to the fact we converted the raw data into a customized efficient data type. Briefly speaking, we try to use all non-zero expressed genes as input for pre-training and there is a max length by default set to 1200. For any input cell that has more non-zero genes, the input will be randomly sampled to that max length.

Currently, you can find the code for pre-training at the `dev-temp` branch, and there is an example script to run the training at https://github.com/bowang-lab/scGPT/blob/dev-temp/examples/pretrain.py

**Comment by yuzhenmao** [comment]
Hi, thank you for the reply! I have looked at the pretrain.py file, and it seems that you did not do any pre-processing such as log1p or hvg. The raw dataset is directly used for the processes you mentioned above (e.g., cutting to max_length, sampling). Am I correct?

**Comment by subercui** [comment]
Hi, yes, mostly so. I just want to highlight that the expression values have been binned as in the `collator`, here
https://github.com/bowang-lab/scGPT/blob/4068d67caaac1e28d56964da68e0214817e38428/examples/pretrain.py#L631-L642

**Comment by yuzhenmao** [comment]
I see. Thanks a lot!
