### ISSUE TITLE
gene names

### ISSUE THREAD

**Issue by karasikov** [bowang-lab/scGPT#117]
Hi there

I'm trying to run the pre-trained scGPT models on a custom dataset with the gene names specified in the Ensembl convention.
However, scGPT seems to use a mix, which I'm trying to understand.

I managed to resolve most of the gene names from https://drive.google.com/drive/folders/1oWh_-ZRdhtoGQ2Fw24HP41FgLoomVo-y?usp=sharing
but I'm still having issues with some.

Also, many gene names seem to be ambiguous.
For instance, there are these two entries in vocab.json
```
"RP11-309M23.1_ENSG00000237531": 24395,
"RP11-309M23.1": 36624,
```
Do these correspond to different genes or the same?

Also, it would be great if you could point me to the place explaining how this dictionary was constructed.

Thanks!

**Comment by subercui** [comment]
Hi, thank you for the question. You can find the mapping between Ensembl IDs and names at https://github.com/bowang-lab/scGPT/discussions/107#discussioncomment-7460340 . Since we utilized the data from CellXGene for pretraining, the mapping is inherited from their schema. You can find the description of their gene metainfo at https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#feature_name
