### ISSUE TITLE
Slow sampling in DataCollator

### ISSUE THREAD

**Issue by yuzhenmao** [bowang-lab/scGPT#118]
Hi, thank you very much for the amazing work! I noticed that in https://github.com/bowang-lab/scGPT/blob/dev-temp/scgpt/data_collator.py#L450, scGPT uses random_sample to replace the truncate for each input sample of the mini-batch. I am wondering if this process would be very slow, especially for multi-gpu training. Did you find this situation during the pretraining? Thank you!

**Comment by yuzhenmao** [comment]
I just found scGPT seems to move the data to gpu during the sampling: https://github.com/bowang-lab/scGPT/blob/dev-temp/scgpt/data_collator.py#L469. May I ask how to achieve this in the multiple-GPU setting? Thank you very much!

**Comment by subercui** [comment]
Hi, thank you for the questions. So far, the random sample step seems fine because pytorch has this prefetch to load data in advance https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader . If you have any suggestion about how to implement this more efficiently, please let me know, and feel free to open a PR.

it seems you closed the issue. Did you resolve the other question?

**Comment by yuzhenmao** [comment]
Hi, thank you for the reply! I closed this issue because I found that random sampling is not that slow, no matter whether we move the data to GPU or not. The reason is very likely the prefetch you shared with me. Thanks again.
