### ISSUE TITLE
Questions about GRN inference

### ISSUE THREAD

**Issue by HelloWorldLTY** [bowang-lab/scGPT#26]
Hi, I intend to clarify one term in the GRN inference process. If we consider regulatory network, one important thing is to identify transcript factor and the regulatory relation should be from TF to genes. Therefore, the regulatory network is a direct graph. However, in the inference process of scGPT, the network is undirect, more like a co-expressed network. Is my understanding correct? Thanks a lot.

**Comment by subercui** [comment]
Hi, we used two strategies for the gene network analysis (1) gene embeddings (2) attention weights. It is true the similarities of gene embeddings are undirected. On the other hand, the attention weights are directed. We think it can be viewed as the influence from the key to the query, since the attention is used to update the embedding of the query.
