### ISSUE TITLE
Input Length for scMultiomic Data?

### ISSUE THREAD

**Issue by AaronNing** [bowang-lab/scGPT#28]
Hi, 
Thanks for your great work. I wonder what is the max length for multiomic inputs? As stated in the preprint,
> 1,200 highly variable genes, 4,000 highly variable peaks, and all 216 protein features were used

Does it mean that you have a max length of 5200 tokens for, e.g., 10X Multiome PBMC data? Will this cause memory/efficiency issues?
Thanks!

**Comment by subercui** [comment]
The max length is a user-defined setting. So if you want more highly variable genes or peaks, you can directly input tokens longer than 5200 tokens. It can cause memory issues if the input length and batch size become too large at the same time.  Nevertheless, there is no hard limit for the max length setting, you can tune it based on your own hardware and scenarios. The good news is since we optimized the implementation using flash-attn, the empirical memory complexity we observed is about linear against input length.
