### ISSUE TITLE
About pretrain code

### ISSUE THREAD

**Issue by wyhsleep** [bowang-lab/scGPT#40]
May I ask when the pretrain code will be released? I would like to try training it on my own dataset.🥹🥹🥹

**Comment by subercui** [comment]
Hi, we are currently working on the multi-omics tutorial setup and relaxing the dependency requirements, since there are several issues reporting about the flash-attn installation. Once these are completed, we'll have time to wrap up and release the code related to pretraining and data collection. Hopefully, that will be completed by next weekend.

In the meantime, how large is your dataset? If you have less than 100K cells, I'll recommend you try the "finetuning-integration" pipeline following the example code. It can usually work well as self-supervised training and should generate dataset-specific cell and gene embeddings.

Thank you!

**Comment by wyhsleep** [comment]
Oh that's great, thank you very much for your work!
