### ISSUE TITLE
Small edit to evaluation metric

### ISSUE THREAD

**Issue by nmahieu-empresstx** [bowang-lab/scGPT#68]
https://github.com/bowang-lab/scGPT/blob/8b1705d109288e09226e3c99d5b247ff39a13805/tutorials/Tutorial_Attention_GRN.ipynb#L1248

This data frame includes 15,000 genes.  Should be filtered by the BHLHE40|Average column to validate.  

`set(gene_list).intersection(set(df[df["BHLHE40|Average"]>500]['Target_genes'].values)), len(set(gene_list).intersection(set(df['Target_genes'].values)))`

**Comment by subercui** [comment]
Hi, your proposal would set a stricter threshold when visualizing the overlap with chip-atlas results, thanks for your suggestion. We originally chose to use the "target genes" in the raw list of https://chip-atlas.dbcls.jp/data/hg38/target/BHLHE40.10.tsv downloaded from the chip-atlas. I think their strategy to identify these targets was to use the highest peak-call MACS2 score across the experiments (instead of using the average score). Please see the description here https://github.com/inutano/chip-atlas/wiki#5-target-genes about how they computed the target gene list, where they indicated a thresholding at MACS2 Q-value < 1E-05. On the other hand, we would agree that the average MACS2 score can be a good way to show the potential significance of the binding pair. We will work on a better visualization to show this information in the tutorial, for example, by showing the edges in the network figure using a color spectrum for different MACS2 average scores.
