### ISSUE TITLE
scGPTHub submit jobs. 

### ISSUE THREAD

**Issue by MinLee323** [bowang-lab/scGPT#73]
Hi! When I am using scGPTHub, the website, I met a problem. I successfully submitted the job, but scGPT analysis failed. So, what is the information should be contained in the H5ad?

This is the structure of H5ad I submitted. 
AnnData object with n_obs × n_vars = 29239 × 60646
    obs: 'cell_names', 'celltype', 'batch'
    var: 'gene_names'

Thanks!

**Comment by subercui** [comment]
Hi, thank you for the question! Since scGPTHub is itself a separate service, we would need to log into the backend and see the specific logs of the job you run. So currently, we suggest you contact via the support email so that we can know the job and account. You can find the contact email address listed in the email you should have received when the job finished.

Could you please simply copy the above message in the email? Thank you in advance for your understanding. I will close this issue for now, but please let me know if you can not find the contact email or have other questions.
