### ISSUE TITLE
another bug in preprocess.py 

### ISSUE THREAD

**Issue by annezxu** [bowang-lab/scGPT#84]
I found a serious error of preprocess.py occurs also during binning, at line 183: 

bins = np.quantile(non_zero_row, np.linspace(0, 1, n_bins - 1))

It crashed because in step 5 (subset hvg), the highly variable genes may cause some rows to contain all zero data and as a result, this line throws an exception. This is hard to fix because step 6 relies on the result of sc.pp.highly_variable_genes in step 5. A potential solution is to remove all-zero data after processing in subset hvg, but then the shape might not match and this could lead to more errors.  

For now, I temporarily removed the affected sample row before preprocessing manually, but I think there needs to be more patching up in scGPT's internal code. Thanks!

**Comment by subercui** [comment]
Hi @annezxu , thank you so much for bringing it up. I currently think maybe it is still worth throwing an exception for the case you mentioned, but for sure the error message should be better constructed. This is because I think if several or even many cells contain no gene expressions, then it makes no sense to process or even train on them later. A better suggestion would be to inform the user to either remove the cells or to use more highly variable genes. Let me know what you think about this and I can make the update

**Comment by annezxu** [comment]
Hi @subercui, thanks for responding! I think it would still be best to resolve this issue internally, maybe remove the cells with no gene expression since they tend to only appear after preprocessing. Additionally, maybe it would be better to print a warning and not throw an exception since that shuts down the program, because when I integrate multiple datasets, it's difficult to trace back and manually exclude rows as the error is so late into the program.

**Comment by subercui** [comment]
Thanks for the suggestion. Now the cells with zero rows are handled. Please see the new commit
