### ISSUE TITLE
Weight initialization of nn.Embedding

### ISSUE THREAD

**Issue by SyedA5688** [bowang-lab/scGPT#9]
Hi, thank you for your great work!

I had a question regarding the weight initialization of nn.Embedding in your model. In scgpt/model/model.py, on line 147, you initialize the embedding table with a range [-0.1, 0.1]. It seems from the comments that this line of code is under question, have you found this initialization to be helpful or should we remove it?

**Comment by subercui** [comment]
Hi, we are still investigating the initialization in the pretraining setting. If you want to fine-tune the model, the line should make no difference since layer weights will be loaded later from the pretrained model. If you want to train a model from scratch for a specific task, the line should be safe to remove, and so far it has little influence when working in this setting.
